import { Inter } from 'next/font/google'
import './globals.css'

import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Food goodies',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <nav className='border-b p-8'>
            <ul className='flex gap-8 container font-medium'>
              <li><Link href="/meals">Meals</Link></li>
              <li><Link href="/meals/share">Share Meals</Link></li>
              <li><Link href="/community">Community</Link></li>
            </ul>
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
